/** FLUXLAB editor state: commands are the only synchronous project mutation path and preserve monotonic revisions. */
import { parseCircuitProjectV2 } from "../../domain/project/project-schema";
import type { CircuitProjectV2, ComponentInstance, ComponentLayout, Diagnostic, DomainResult } from "../../domain/project/project-v2";
export type ProjectCommand = { type: "component/replace"; component: ComponentInstance } | { type: "layout/componentSet"; componentId: string; layout: ComponentLayout } | { type: "project/rename"; title: string };
export interface ProjectEditorState { past: CircuitProjectV2[]; present: CircuitProjectV2; future: CircuitProjectV2[]; diagnostics: Diagnostic[]; }
export type ProjectEditorAction = { type: "hydrate"; project: CircuitProjectV2 } | { type: "command"; command: ProjectCommand; changedAt: string } | { type: "undo"; changedAt: string } | { type: "redo"; changedAt: string };
const error = (code: string): DomainResult<never> => ({ ok: false, diagnostics: [{ severity: "error", code, message: "The requested project change is invalid.", blocksRun: true }] });
export function applyProjectCommand(project: CircuitProjectV2, command: ProjectCommand, changedAt: string): DomainResult<CircuitProjectV2> { let next: CircuitProjectV2; let electrical = false; if (command.type === "layout/componentSet") { if (!project.schematic.components.some((item) => item.id === command.componentId)) return error("PROJECT_UNKNOWN_COMPONENT"); if (JSON.stringify(project.layout.components[command.componentId]) === JSON.stringify(command.layout)) return { ok: true, value: project, diagnostics: [] }; next = { ...project, updatedAt: changedAt, revision: project.revision + 1, layout: { ...project.layout, components: { ...project.layout.components, [command.componentId]: command.layout } } }; } else if (command.type === "component/replace") { const index = project.schematic.components.findIndex((item) => item.id === command.component.id); if (index < 0) return error("PROJECT_UNKNOWN_COMPONENT"); if (JSON.stringify(project.schematic.components[index]) === JSON.stringify(command.component)) return { ok: true, value: project, diagnostics: [] }; const components: ComponentInstance[] = project.schematic.components.slice(); components[index] = command.component; electrical = true; next = { ...project, updatedAt: changedAt, revision: project.revision + 1, electricalRevision: project.electricalRevision + 1, schematic: { ...project.schematic, components } }; } else { if (!command.title.trim() || command.title === project.title) return { ok: true, value: project, diagnostics: [] }; next = { ...project, title: command.title.trim(), updatedAt: changedAt, revision: project.revision + 1 }; } const validated = parseCircuitProjectV2(next); return validated.ok ? { ok: true, value: next, diagnostics: electrical ? [] : [] } : validated; }
export function projectReducer(state: ProjectEditorState, action: ProjectEditorAction): ProjectEditorState { if (action.type === "hydrate") return { past: [], present: action.project, future: [], diagnostics: [] }; if (action.type === "command") { const result = applyProjectCommand(state.present, action.command, action.changedAt); return result.ok && result.value !== state.present ? { past: [...state.past, state.present].slice(-50), present: result.value, future: [], diagnostics: result.diagnostics } : { ...state, diagnostics: result.diagnostics }; } const source = action.type === "undo" ? state.past : state.future; if (!source.length) return state; const restored = source.at(-1)!; const electricalChanged = JSON.stringify(restored.schematic) !== JSON.stringify(state.present.schematic) || JSON.stringify(restored.models) !== JSON.stringify(state.present.models) || JSON.stringify(restored.analyses) !== JSON.stringify(state.present.analyses) || JSON.stringify(restored.probes) !== JSON.stringify(state.present.probes); const present = { ...restored, revision: state.present.revision + 1, electricalRevision: state.present.electricalRevision + (electricalChanged ? 1 : 0), updatedAt: action.changedAt }; return action.type === "undo" ? { past: state.past.slice(0, -1), present, future: [state.present, ...state.future].slice(0, 50), diagnostics: [] } : { past: [...state.past, state.present].slice(-50), present, future: state.future.slice(0, -1), diagnostics: [] }; }
