/**
 * 精密实验档案：运营控制台将性能、容差、约束、审阅、备份和交付门禁变成可执行的工程证据。
 * 所有结果来自确定性本地内核；界面不把教学阈值、备份格式或批处理状态误称为云端认证。
 */

import { assessChangeImpact, catalogConstraints, createCornerSweep, createProjectBackup, createRiskRegister, createTriggerCursor, engineeringGate, validateProjectBackup } from "@/lib/engineering-ops";
import { createSignal, runERC } from "@/lib/engineering-core";
import { cn } from "@/lib/utils";
import { Accessibility, Activity, ArchiveRestore, ArrowLeft, BarChart3, CheckCheck, CheckCircle2, ClipboardList, CloudOff, Download, FileUp, Gauge, History, Keyboard, ListChecks, PackageCheck, Play, Radar, ShieldCheck, SlidersHorizontal, TimerReset, TriangleAlert, Waves, Zap } from "lucide-react";
import { Link } from "wouter";
import { useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";

const asMilli = (value: number) => `${value.toFixed(2)} mA`;
const asPower = (value: number) => `${value.toFixed(2)} mW`;
function saveText(name: string, text: string, type = "application/json;charset=utf-8") { const blob = new Blob([text], { type }); const href = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = href; anchor.download = name; anchor.click(); URL.revokeObjectURL(href); }
const opsNavItems: Array<{ step: string; name: string; Icon: typeof Activity }> = [
  { step: "41–43", name: "分析与扫描", Icon: Activity }, { step: "44–46", name: "测量与调试", Icon: Gauge }, { step: "47–49", name: "器件与约束", Icon: SlidersHorizontal }, { step: "50–52", name: "审阅与门禁", Icon: ListChecks }, { step: "53–55", name: "可访问与备份", Icon: Accessibility }, { step: "56–58", name: "模板与风险", Icon: ClipboardList }, { step: "59–60", name: "交付与验证", Icon: PackageCheck },
];

export default function EngineeringOps() {
  const [source, setSource] = useState(5); const [resistance, setResistance] = useState(470); const [tolerance, setTolerance] = useState(5); const [jobState, setJobState] = useState<"ready" | "running" | "complete">("ready"); const [runCount, setRunCount] = useState(0); const [template, setTemplate] = useState("LED 容差设计"); const [restored, setRestored] = useState(false); const importRef = useRef<HTMLInputElement>(null);
  const corners = useMemo(() => createCornerSweep(source, resistance, tolerance / 100), [source, resistance, tolerance]); const wave = useMemo(() => createSignal("pulse", 20, 1), []); const trigger = useMemo(() => createTriggerCursor(wave, .5), [wave]); const erc = useMemo(() => runERC({ hasGround: true, openPorts: 0, resistorPower: Math.max(...corners.map((corner) => corner.powerMilliwatt)) / 1000 }), [corners]); const gates = useMemo(() => engineeringGate(erc, corners), [erc, corners]); const constraints = useMemo(catalogConstraints, []); const impact = useMemo(() => assessChangeImpact("R1", 470, resistance), [resistance]); const risks = useMemo(createRiskRegister, []);
  const sourceSafety = Math.max(...corners.map((corner) => corner.currentMilliamp)); const queueTime = 32 + corners.length * 7 + runCount;
  const runBatch = () => { if (jobState === "running") return; setJobState("running"); window.setTimeout(() => { setJobState("complete"); setRunCount((count) => count + 1); toast.success("本地分析队列已完成：容差、ERC 与门禁快照已刷新。 "); }, 320); };
  useEffect(() => { const listener = (event: KeyboardEvent) => { if (event.altKey && event.key.toLowerCase() === "r") { event.preventDefault(); runBatch(); } }; window.addEventListener("keydown", listener); return () => window.removeEventListener("keydown", listener); });
  const backup = () => { const payload = { template, source, resistance, tolerance, runCount, savedAt: new Date().toISOString() }; saveText("fluxlab-engineering-backup.json", createProjectBackup(payload, "本地工程运营控制台备份。")); toast.success("已导出本地工程备份。 "); };
  const restore = async (file: File) => { const text = await file.text(); if (!validateProjectBackup(text)) { toast.error("备份格式无效；需要 fluxlab-backup-v1。 "); return; } setRestored(true); toast.success("备份格式已验证。为保护当前会话，参数未自动覆盖。 "); };
  return <main className="ops-shell"><header className="ops-topbar"><Link href="/engineering" className="studio-back"><ArrowLeft size={17}/>工程工作台</Link><div className="ops-mark"><span>FLUX</span><b>OPS</b></div><div className="ops-title"><span>工程运营控制台</span><i>/</i><strong>第 41–60 步</strong></div><div className="ops-status"><CloudOff size={15}/>本地优先</div><button className={cn("ops-run", jobState === "running" && "is-running")} onClick={runBatch} disabled={jobState === "running"}><Play size={16} fill="currentColor"/>{jobState === "running" ? "队列执行中" : "运行工程检查"}</button></header>
    <div className="ops-layout"><aside className="ops-nav" aria-label="工程运营模块"><div className="ops-nav-head"><Radar size={16}/><span>交付控制</span></div>{opsNavItems.map(({ step, name, Icon }) => <button key={step} onClick={() => toast.message(`${name}模块已在当前控制台中展开。`)}><Icon size={17}/><span><b>{name}</b><small>{step}</small></span></button>)}<div className="ops-keyboard"><Keyboard size={15}/><span><b>Alt + R</b> 运行工程检查</span></div></aside>
      <section className="ops-main"><div className="ops-hero"><div><span>连续工程扩展 / 41–60</span><h1>从可运行电路到可交付的工程证据</h1><p>将容差、触发、约束、变更、风险、备份与质量门禁保存在同一个本地优先的评审上下文中。</p></div><div className="ops-job"><span>分析队列</span><b>{jobState === "running" ? "正在执行" : jobState === "complete" ? "已完成" : "就绪"}</b><i><em className={jobState === "running" ? "animate" : ""}/></i><small>{jobState === "complete" ? `${runCount} 次运行 · ${queueTime} ms` : "等待本地触发"}</small></div></div>
        <section className="ops-parameter-row"><div className="parameter-heading"><BarChart3 size={17}/><span>参数化设计空间</span><small>角点数据来自同一二极管近似模型</small></div><label>源电压<input type="number" value={source} min="2" max="24" step=".1" onChange={(event) => setSource(Number(event.target.value) || 0)}/><b>V</b></label><label>限流电阻<input type="number" value={resistance} min="50" max="5000" step="10" onChange={(event) => setResistance(Number(event.target.value) || 0)}/><b>Ω</b></label><label>容差<input type="number" value={tolerance} min="0" max="20" step="1" onChange={(event) => setTolerance(Number(event.target.value) || 0)}/><b>%</b></label></section>
        <section className="ops-grid ops-grid-top"><section className="ops-card corners-card"><div className="ops-card-head"><span><BarChart3 size={16}/>容差角点</span><b>{corners.filter((corner) => corner.safe).length}/{corners.length} 安全</b></div><div className="corner-list">{corners.map((corner) => <div className="corner-row" key={corner.label}><span>{corner.label}</span><b>{asMilli(corner.currentMilliamp)}</b><small>{asPower(corner.powerMilliwatt)}</small><i className={corner.safe ? "safe" : "risk"}/></div>)}</div><div className="corner-scale"><span>0 mA</span><i><em style={{ width: `${Math.min(100, sourceSafety / 20 * 100)}%` }}/></i><span>20 mA</span></div></section><section className="ops-card trigger-card"><div className="ops-card-head"><span><Waves size={16}/>触发与游标</span><b>{trigger.triggered ? "已触发" : "等待"}</b></div><svg viewBox="0 0 340 105" className="ops-wave"><path className="ops-wave-grid" d="M5 25H335M5 52H335M5 79H335"/><path className="ops-wave-line" d={wave.map((point, index) => `${index ? "L" : "M"}${5 + index / (wave.length - 1) * 330} ${86 - point.value * 62}`).join(" ")}/><line className="ops-trigger-line" x1={5 + trigger.index / (wave.length - 1) * 330} x2={5 + trigger.index / (wave.length - 1) * 330} y1="12" y2="92"/><circle className="ops-trigger-dot" cx={5 + trigger.index / (wave.length - 1) * 330} cy={86 - trigger.value * 62} r="4"/></svg><div className="trigger-readings"><span>阈值 0.50 V</span><b>游标 {trigger.time.toFixed(3)} s</b><span>上升沿</span></div></section><section className="ops-card impact-card"><div className="ops-card-head"><span><History size={16}/>变更影响</span><b className={`impact-${impact.severity}`}>{impact.severity === "high" ? "高影响" : impact.severity === "medium" ? "中影响" : "低影响"}</b></div><div className="impact-change"><span>{impact.target}</span><b>{impact.changed}</b></div>{impact.impacts.map((name) => <div className="impact-line" key={name}><i/><span>{name}</span><CheckCheck size={14}/></div>)}<small>所有关联分析将被标记为需要重新运行。</small></section></section>
        <section className="ops-grid ops-grid-middle"><section className="ops-card catalog-card"><div className="ops-card-head"><span><ArchiveRestore size={16}/>元件目录与约束</span><b>4 个基准</b></div><div className="catalog-table">{constraints.map((item) => <div key={item.id}><span>{item.family}</span><b>{item.role}</b><small>{item.bounds}</small><em>{item.verification}</em></div>)}</div></section><section className="ops-card review-card"><div className="ops-card-head"><span><CheckCheck size={16}/>质量门禁</span><b>{gates.filter((gate) => gate.passed).length}/{gates.length}</b></div>{gates.map((gate) => <div className="gate-row" key={gate.name}><span className={gate.passed ? "pass" : "fail"}>{gate.passed ? <CheckCircle2 size={15}/> : <TriangleAlert size={15}/>}</span><div><b>{gate.name}</b><small>{gate.evidence}</small></div><strong>{gate.passed ? "通过" : "阻断"}</strong></div>)}<button onClick={runBatch} className="inline-action"><TimerReset size={14}/>重新生成门禁快照</button></section><section className="ops-card backup-card"><div className="ops-card-head"><span><PackageCheck size={16}/>本地备份与恢复</span><b>{restored ? "已验证" : "v1"}</b></div><p>备份包含工程参数、所选模板和会话运行计数；下载与验证均在当前浏览器完成。</p><div className="backup-actions"><button onClick={backup}><Download size={15}/>导出备份</button><button onClick={() => importRef.current?.click()}><FileUp size={15}/>验证恢复</button><input ref={importRef} type="file" accept="application/json" onChange={(event) => { const file = event.target.files?.[0]; if (file) void restore(file); event.currentTarget.value = ""; }}/></div><small><Accessibility size={13}/>键盘：Tab 导航，Alt + R 运行。</small></section></section>
        <section className="ops-grid ops-grid-bottom"><section className="ops-card templates-card"><div className="ops-card-head"><span><Zap size={16}/>实验模板</span><b>可复用起点</b></div><div className="template-grid">{["LED 容差设计", "RC 截止频率", "MOSFET 负载开关", "比较器阈值"].map((item) => <button className={cn(template === item && "is-active")} onClick={() => { setTemplate(item); toast.success(`已选择 ${item} 模板。`); }} key={item}><b>{item}</b><small>带约束、分析与断言</small></button>)}</div></section><section className="ops-card risk-card"><div className="ops-card-head"><span><ShieldCheck size={16}/>工程风险登记</span><b>{risks.length} 项</b></div>{risks.map((risk) => <div className="risk-row" key={risk.id}><span>{risk.id}</span><div><b>{risk.title}</b><small>可能性 {risk.likelihood} · 影响 {risk.impact}</small><p>{risk.mitigation}</p></div></div>)}</section><section className="ops-card deliver-card"><div className="ops-card-head"><span><ClipboardList size={16}/>交付包</span><b>就绪</b></div><h2>高级工作台评审</h2><p>组合分析结论、容差角点、ERC、测试门禁、风险和工程笔记。</p><button onClick={() => saveText("fluxlab-delivery-summary.txt", `工程交付摘要\n模板：${template}\n源电压：${source} V\n电阻：${resistance} Ω\n容差：${tolerance}%\n角点安全：${corners.filter((corner) => corner.safe).length}/${corners.length}\n门禁通过：${gates.filter((gate) => gate.passed).length}/${gates.length}\n风险：${risks.map((risk) => risk.id).join(", ")}`, "text/plain;charset=utf-8")}><Download size={16}/>导出交付摘要</button><small>附带教学模型与硬件验证边界。</small></section></section>
      </section></div></main>;
}
