/** FLUXLAB SPICE trust boundary: only this browser-safe parser may normalize or approve model/circuit text. */
import { sha256Hex } from "../domain/project/canonical";
import type { CircuitProjectV2, Diagnostic, DomainResult, ModelDefinition, SpiceDeviceFamily, SubcircuitInterface } from "../domain/project/project-v2";

export type SpiceSourceOrigin = "user-cir" | "project-model" | "bundled-model" | "migration" | "stored-model";
export type SpiceSourceMode = "editable-circuit" | "opaque-model";
export interface ParsedSpiceStatementBase { text: string; startLine: number; endLine: number; scope: { kind: "top-level" } | { kind: "subcircuit"; name: string }; }
export type ParsedSpiceValue = { kind: "finite-number"; sourceToken: string; valueSI: number } | { kind: "parameter-reference"; sourceToken: string; name: string };
export type ParsedIndependentSource = { dc?: number; ac?: { magnitude: number; phaseDeg: number }; transient?: { kind: "pulse" | "sin" | "pwl"; values: number[] } };
export type ParsedAnalysisDirective = { kind: "op" } | { kind: "dc" | "tran" | "ac"; values: number[]; tokens: string[] };
export interface ParsedParameterAssignment { name: string; value: ParsedSpiceValue; }
export type ParsedSpiceElement =
  | (ParsedSpiceStatementBase & { kind: "element"; device: "R" | "C" | "L"; name: string; positiveNode: string; negativeNode: string; value: ParsedSpiceValue })
  | (ParsedSpiceStatementBase & { kind: "element"; device: "V" | "I"; name: string; positiveNode: string; negativeNode: string; source: ParsedIndependentSource })
  | (ParsedSpiceStatementBase & { kind: "element"; device: "S"; name: string; positiveNode: string; negativeNode: string; controlPositiveNode: string; controlNegativeNode: string; modelName: string })
  | (ParsedSpiceStatementBase & { kind: "element"; device: "D"; name: string; anodeNode: string; cathodeNode: string; modelName: string; area?: ParsedSpiceValue })
  | (ParsedSpiceStatementBase & { kind: "element"; device: "Q"; name: string; collectorNode: string; baseNode: string; emitterNode: string; substrateNode?: string; modelName: string; area?: ParsedSpiceValue })
  | (ParsedSpiceStatementBase & { kind: "element"; device: "M"; name: string; drainNode: string; gateNode: string; sourceNode: string; bulkNode: string; modelName: string; length: ParsedSpiceValue; width: ParsedSpiceValue; multiplicity?: ParsedSpiceValue })
  | (ParsedSpiceStatementBase & { kind: "element"; device: "X"; name: string; orderedNodes: string[]; subcircuitName: string; orderedOverrides: ParsedParameterAssignment[] });
export type ParsedSpiceStatement =
  | (ParsedSpiceStatementBase & { kind: "title" | "terminator" | "comment" })
  | ParsedSpiceElement
  | (ParsedSpiceStatementBase & { kind: "analysis"; analysis: ParsedAnalysisDirective })
  | (ParsedSpiceStatementBase & { kind: "model"; name: string; family: SpiceDeviceFamily; orderedParameters: ParsedParameterAssignment[] })
  | (ParsedSpiceStatementBase & { kind: "subckt-start"; name: string; orderedPins: string[]; orderedDefaults: ParsedParameterAssignment[] })
  | (ParsedSpiceStatementBase & { kind: "subckt-end"; name?: string })
  | (ParsedSpiceStatementBase & { kind: "parameter"; orderedAssignments: ParsedParameterAssignment[] });
export type ParsedDeclarationBlock =
  | { kind: "model"; name: string; family: SpiceDeviceFamily; startLine: number; endLine: number; normalizedSource: string }
  | { kind: "subcircuit"; interface: SubcircuitInterface; startLine: number; endLine: number; normalizedSource: string; statements: ParsedSpiceStatement[]; externalModelNames: string[]; externalSubcircuitNames: string[] };
export interface ParsedSpiceSource { normalizedSource: string; statements: ParsedSpiceStatement[]; declarationBlocks: ParsedDeclarationBlock[]; models: Array<{ name: string; family: SpiceDeviceFamily }>; subcircuits: SubcircuitInterface[]; utf8Bytes: number; sha256: string; }

const token = /^[A-Za-z0-9_][A-Za-z0-9_.-]{0,63}$/;
const refdes = /^[A-Za-z][A-Za-z0-9_]{0,31}$/;
const parameter = /^[A-Za-z_][A-Za-z0-9_]{0,63}$/;
const forbiddenSymbol = new Set(["__proto__", "prototype", "constructor"]);
const suffixes: Array<[string, number]> = [["meg", 1e6], ["mil", 25.4e-6], ["t", 1e12], ["g", 1e9], ["k", 1e3], ["m", 1e-3], ["u", 1e-6], ["n", 1e-9], ["p", 1e-12], ["f", 1e-15]];
const unsafeDirective = /(?:^|\s)\.(?:control|endc|shell|include|lib|options|save|print|plot|measure)\b/i;
const numberGrammar = /^([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?)([a-z]+)?$/i;

function diagnostic(code: string, message: string, startLine: number, endLine: number, origin: SpiceSourceOrigin): Diagnostic { return { severity: "error", code, message, location: { sourceName: origin, line: startLine, endLine }, blocksRun: true }; }
function safeToken(value: string, kind: "token" | "refdes" | "parameter" = "token"): boolean { const pattern = kind === "refdes" ? refdes : kind === "parameter" ? parameter : token; return pattern.test(value) && !forbiddenSymbol.has(value.toLowerCase()); }
function parseNumber(sourceToken: string): number | null { const match = sourceToken.match(numberGrammar); if (!match) return null; const base = Number(match[1]); if (!Number.isFinite(base)) return null; const suffix = match[2]?.toLowerCase(); const multiplier = suffix ? suffixes.find(([name]) => name === suffix)?.[1] : 1; if (multiplier === undefined) return null; const value = base * multiplier; return Number.isFinite(value) && (value !== 0 || base === 0) ? value : null; }
function parseValue(sourceToken: string, inSubcircuit: boolean): ParsedSpiceValue | null { const parameterReference = sourceToken.match(/^\{([A-Za-z_][A-Za-z0-9_]*)\}$/); if (parameterReference) return inSubcircuit && safeToken(parameterReference[1], "parameter") ? { kind: "parameter-reference", sourceToken, name: parameterReference[1] } : null; const valueSI = parseNumber(sourceToken); return valueSI === null ? null : { kind: "finite-number", sourceToken, valueSI }; }
function splitAssignments(tokens: string[], inSubcircuit: boolean): ParsedParameterAssignment[] | null { const values: ParsedParameterAssignment[] = []; for (const item of tokens) { const match = item.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.+)$/); if (!match || !safeToken(match[1], "parameter")) return null; const value = parseValue(match[2], inSubcircuit); if (!value) return null; values.push({ name: match[1], value }); } return values; }
function normalizePhysicalLines(source: string, origin: SpiceSourceOrigin): { lines: Array<{ text: string; startLine: number; endLine: number }>; normalized: string; diagnostics: Diagnostic[] } {
  const diagnostics: Diagnostic[] = [];
  if (/^\uFEFF|[\u0000\u0001-\u0008\u000B\u000C\u000E-\u001F\u007F-\u009F]/.test(source)) return { lines: [], normalized: "", diagnostics: [diagnostic("SPICE_INVALID_CONTROL", "SPICE source contains an unsafe control character.", 1, 1, origin)] };
  const normalized = source.replace(/\r\n?/g, "\n");
  const physical = normalized.split("\n");
  const lines: Array<{ text: string; startLine: number; endLine: number }> = [];
  for (let index = 0; index < physical.length; index += 1) {
    const raw = physical[index];
    if (new TextEncoder().encode(raw).byteLength > 65_536) { diagnostics.push(diagnostic("SPICE_LINE_TOO_LONG", "A physical SPICE line exceeds the allowed UTF-8 byte limit.", index + 1, index + 1, origin)); continue; }
    if (/^\s*\+/.test(raw)) { const previous = lines.at(-1); if (!previous) diagnostics.push(diagnostic("SPICE_ORPHAN_CONTINUATION", "A continuation line has no preceding statement.", index + 1, index + 1, origin)); else { previous.text += ` ${raw.replace(/^\s*\+\s?/, "")}`; previous.endLine = index + 1; } }
    else lines.push({ text: raw, startLine: index + 1, endLine: index + 1 });
  }
  for (const line of lines) if (new TextEncoder().encode(line.text).byteLength > 65_536) diagnostics.push(diagnostic("SPICE_LINE_TOO_LONG", "A joined SPICE statement exceeds the allowed UTF-8 byte limit.", line.startLine, line.endLine, origin));
  return { lines, normalized, diagnostics };
}
function sourceFromTokens(tokens: string[]): ParsedIndependentSource | null {
  if (!tokens.length) return {};
  const output: ParsedIndependentSource = {}; let index = 0;
  const setDc = (value: string) => { const parsed = parseNumber(value); if (parsed === null) return false; output.dc = parsed; return true; };
  if (/^dc$/i.test(tokens[index] ?? "")) { if (!setDc(tokens[index + 1] ?? "")) return null; index += 2; } else if (!/^(ac|pulse|sin|pwl)$/i.test(tokens[index] ?? "")) { if (!setDc(tokens[index])) return null; index += 1; }
  if (/^ac$/i.test(tokens[index] ?? "")) { const magnitude = parseNumber(tokens[index + 1] ?? ""); const phaseDeg = parseNumber(tokens[index + 2] ?? "0"); if (magnitude === null || magnitude < 0 || phaseDeg === null) return null; output.ac = { magnitude, phaseDeg }; index += tokens[index + 2] === undefined ? 2 : 3; }
  if (index < tokens.length) { const match = tokens.slice(index).join(" ").match(/^(pulse|sin|pwl)\s*\((.*)\)$/i); if (!match) return null; const values = match[2].trim().split(/[\s,]+/).filter(Boolean).map(parseNumber); if (values.some((value) => value === null)) return null; output.transient = { kind: match[1].toLowerCase() as "pulse" | "sin" | "pwl", values: values as number[] }; }
  return output;
}
function modelFamily(value: string): SpiceDeviceFamily | null { const normalized = value.toUpperCase(); if (normalized === "SW") return "switch"; if (normalized === "D") return "diode"; if (normalized === "NPN") return "npn"; if (normalized === "PNP") return "pnp"; if (normalized === "NMOS") return "nmos"; if (normalized === "PMOS") return "pmos"; return null; }

export async function parseAndValidateSpiceSource(source: string, origin: SpiceSourceOrigin, mode: SpiceSourceMode): Promise<DomainResult<ParsedSpiceSource>> {
  const physical = normalizePhysicalLines(source, origin); const diagnostics = [...physical.diagnostics]; const statements: ParsedSpiceStatement[] = []; const models: Array<{ name: string; family: SpiceDeviceFamily }> = []; const subcircuits: SubcircuitInterface[] = []; const declarations: ParsedDeclarationBlock[] = []; let activeSubckt: { statementIndex: number; name: string; startLine: number; interface: SubcircuitInterface } | undefined; let sawTitle = false; let sawEnd = false;
  const reject = (code: string, message: string, line: { startLine: number; endLine: number }) => diagnostics.push(diagnostic(code, message, line.startLine, line.endLine, origin));
  for (const line of physical.lines) {
    const text = line.text.trim(); if (!text) continue; if (sawEnd) { reject("SPICE_MISPLACED_END", "No statement may follow .end.", line); continue; }
    const base: ParsedSpiceStatementBase = { text: line.text, startLine: line.startLine, endLine: line.endLine, scope: activeSubckt ? { kind: "subcircuit", name: activeSubckt.name } : { kind: "top-level" } };
    if (/^[*;]/.test(text)) { statements.push({ ...base, kind: "comment" }); continue; }
    if (unsafeDirective.test(text) || /(?:\$\(|`|[\\/])/.test(text)) { reject("SPICE_FORBIDDEN_DIRECTIVE", "This directive or path-like source is not permitted.", line); continue; }
    if (!text.startsWith(".")) {
      const tokens = text.split(/\s+/); const device = tokens[0][0]?.toUpperCase();
      if (mode === "editable-circuit" && !activeSubckt && !sawTitle && !statements.length && tokens.length < 3) { statements.push({ ...base, kind: "title" }); sawTitle = true; continue; }
      if (!device || !"RCLVISDQMX".includes(device) || !safeToken(tokens[0], "refdes") || (mode === "opaque-model" && !activeSubckt)) { reject("SPICE_UNSUPPORTED_STATEMENT", "This element is not allowed in the current SPICE source mode.", line); continue; }
      const node = (value: string | undefined) => value && safeToken(value) ? value : null; const inSub = Boolean(activeSubckt);
      if (["R", "C", "L"].includes(device)) { const [name, positiveNode, negativeNode, sourceValue, ...rest] = tokens; const value = sourceValue && parseValue(sourceValue, inSub); if (rest.length || !node(positiveNode) || !node(negativeNode) || !value || (!inSub && value.kind !== "finite-number")) reject("SPICE_BAD_ELEMENT", "Passive elements require two safe nodes and one finite value.", line); else statements.push({ ...base, kind: "element", device: device as "R" | "C" | "L", name, positiveNode, negativeNode, value }); continue; }
      if (device === "V" || device === "I") { const [name, positiveNode, negativeNode, ...sourceTokens] = tokens; const parsed = node(positiveNode) && node(negativeNode) ? sourceFromTokens(sourceTokens) : null; if (!parsed) reject("SPICE_BAD_SOURCE", "Independent source syntax is invalid.", line); else statements.push({ ...base, kind: "element", device, name, positiveNode, negativeNode, source: parsed }); continue; }
      if (device === "S") { const [name, positiveNode, negativeNode, controlPositiveNode, controlNegativeNode, modelName, ...rest] = tokens; if (rest.length || !node(positiveNode) || !node(negativeNode) || !node(controlPositiveNode) || !node(controlNegativeNode) || !modelName || !safeToken(modelName)) reject("SPICE_BAD_ELEMENT", "Switch syntax is invalid.", line); else statements.push({ ...base, kind: "element", device: "S", name, positiveNode, negativeNode, controlPositiveNode, controlNegativeNode, modelName }); continue; }
      if (device === "D") { const [name, anodeNode, cathodeNode, modelName, areaToken, ...rest] = tokens; const area = areaToken && parseValue(areaToken, inSub); if (rest.length || !node(anodeNode) || !node(cathodeNode) || !modelName || !safeToken(modelName) || (areaToken && (!area || (area.kind === "finite-number" && area.valueSI <= 0)))) reject("SPICE_BAD_ELEMENT", "Diode syntax is invalid.", line); else statements.push({ ...base, kind: "element", device: "D", name, anodeNode, cathodeNode, modelName, ...(area ? { area } : {}) }); continue; }
      if (device === "Q") { const [name, collectorNode, baseNode, emitterNode, modelName, ...rest] = tokens; if (!node(collectorNode) || !node(baseNode) || !node(emitterNode) || !modelName || !safeToken(modelName) || rest.length > 1) reject("SPICE_BAD_ELEMENT", "BJT syntax is invalid.", line); else { const area = rest[0] && parseValue(rest[0], inSub); if (rest[0] && !area) reject("SPICE_BAD_ELEMENT", "BJT area is invalid.", line); else statements.push({ ...base, kind: "element", device: "Q", name, collectorNode, baseNode, emitterNode, modelName, ...(area ? { area } : {}) }); } continue; }
      if (device === "M") { const [name, drainNode, gateNode, sourceNode, bulkNode, modelName, ...assignments] = tokens; const pairs = splitAssignments(assignments, inSub); const length = pairs?.find((entry) => entry.name.toUpperCase() === "L")?.value; const width = pairs?.find((entry) => entry.name.toUpperCase() === "W")?.value; const multiplicity = pairs?.find((entry) => entry.name.toUpperCase() === "M")?.value; if (!node(drainNode) || !node(gateNode) || !node(sourceNode) || !node(bulkNode) || !modelName || !safeToken(modelName) || !pairs || !length || !width) reject("SPICE_BAD_ELEMENT", "MOSFET syntax requires safe nodes and L/W values.", line); else statements.push({ ...base, kind: "element", device: "M", name, drainNode, gateNode, sourceNode, bulkNode, modelName, length, width, ...(multiplicity ? { multiplicity } : {}) }); continue; }
      const [name, ...tail] = tokens; const divider = tail.findIndex((entry) => /^params:$/i.test(entry)); const positional = divider < 0 ? tail : tail.slice(0, divider); const assignments = splitAssignments(divider < 0 ? [] : tail.slice(divider + 1), inSub); const subcircuitName = positional.at(-1); const orderedNodes = positional.slice(0, -1); if (!subcircuitName || !safeToken(subcircuitName) || !orderedNodes.length || orderedNodes.some((entry) => !safeToken(entry)) || assignments === null) reject("SPICE_BAD_ELEMENT", "Subcircuit syntax is invalid.", line); else statements.push({ ...base, kind: "element", device: "X", name, orderedNodes, subcircuitName, orderedOverrides: assignments }); continue;
    }
    const tokens = text.split(/\s+/); const directive = tokens[0].toLowerCase();
    if (directive === ".model") { const match = text.match(/^\.model\s+([^\s]+)\s+([A-Za-z]+)\s*(?:\((.*)\))?$/i); const family = match && modelFamily(match[2]); const params = match?.[3] ? splitAssignments(match[3].trim().split(/\s+/).filter(Boolean), Boolean(activeSubckt)) : []; if (!match || !family || !safeToken(match[1]) || !params) { reject("SPICE_BAD_MODEL", "Model declaration is invalid.", line); continue; } if (family === "switch") { const values = new Map(params.map((item) => [item.name.toUpperCase(), item.value])); const ron = values.get("RON"); const roff = values.get("ROFF"); if (!["VT", "VH", "RON", "ROFF"].every((name) => values.get(name)?.kind === "finite-number") || ron?.kind !== "finite-number" || roff?.kind !== "finite-number" || ron.valueSI <= 0 || roff.valueSI <= ron.valueSI) { reject("SPICE_BAD_SWITCH_MODEL", "Switch models require finite VT/VH and positive RON/ROFF.", line); continue; } } statements.push({ ...base, kind: "model", name: match[1], family, orderedParameters: params }); models.push({ name: match[1], family }); declarations.push({ kind: "model", name: match[1], family, startLine: line.startLine, endLine: line.endLine, normalizedSource: line.text }); continue; }
    if (directive === ".subckt") { if (activeSubckt) { reject("SPICE_NESTED_SUBCKT", "Nested subcircuits are not allowed.", line); continue; } const rest = tokens.slice(1); const parametersAt = rest.findIndex((item) => /^params:$/i.test(item)); const name = rest[0]; const pins = rest.slice(1, parametersAt < 0 ? undefined : parametersAt); const defaults = splitAssignments(parametersAt < 0 ? [] : rest.slice(parametersAt + 1), true); if (!name || !safeToken(name) || !pins.length || pins.some((pin) => !safeToken(pin)) || !defaults) { reject("SPICE_BAD_SUBCKT", "Subcircuit declaration is invalid.", line); continue; } const interfaceDefinition: SubcircuitInterface = { name, orderedPins: pins, parameterNames: defaults.map((item) => item.name), parameterDefaults: Object.assign(Object.create(null), Object.fromEntries(defaults.filter((item) => item.value.kind === "finite-number").map((item) => [item.name, (item.value as Extract<ParsedSpiceValue, { kind: "finite-number" }>).valueSI]))) }; activeSubckt = { statementIndex: statements.length, name, startLine: line.startLine, interface: interfaceDefinition }; statements.push({ ...base, kind: "subckt-start", name, orderedPins: pins, orderedDefaults: defaults }); continue; }
    if (directive === ".ends") { if (!activeSubckt || (tokens[1] && tokens[1].toUpperCase() !== activeSubckt.name.toUpperCase())) { reject("SPICE_UNPAIRED_SUBCKT", "Subcircuit end does not match an open declaration.", line); continue; } const start = activeSubckt; statements.push({ ...base, kind: "subckt-end", ...(tokens[1] ? { name: tokens[1] } : {}) }); const blockStatements = statements.slice(start.statementIndex); declarations.push({ kind: "subcircuit", interface: start.interface, startLine: start.startLine, endLine: line.endLine, normalizedSource: physical.normalized.split("\n").slice(start.startLine - 1, line.endLine).join("\n"), statements: blockStatements, externalModelNames: blockStatements.filter((statement): statement is Extract<ParsedSpiceElement, { modelName: string }> => statement.kind === "element" && "modelName" in statement).map((statement) => statement.modelName), externalSubcircuitNames: blockStatements.filter((statement): statement is Extract<ParsedSpiceStatement, { kind: "element"; device: "X" }> => statement.kind === "element" && statement.device === "X").map((statement) => statement.subcircuitName) }); subcircuits.push(start.interface); activeSubckt = undefined; continue; }
    if (directive === ".param") { const assignments = splitAssignments(tokens.slice(1), Boolean(activeSubckt)); if (mode !== "opaque-model" || !activeSubckt || !assignments) reject("SPICE_FORBIDDEN_DIRECTIVE", "Parameters are only allowed inside opaque model subcircuits.", line); else statements.push({ ...base, kind: "parameter", orderedAssignments: assignments }); continue; }
    if ([".op", ".dc", ".tran", ".ac"].includes(directive)) { if (mode !== "editable-circuit") { reject("SPICE_FORBIDDEN_DIRECTIVE", "Analysis directives are not allowed in opaque model sources.", line); continue; } const kind = directive.slice(1) as "op" | "dc" | "tran" | "ac"; const values = tokens.slice(1).map(parseNumber); if ((kind === "op" && tokens.length !== 1) || (kind !== "op" && values.some((value) => value === null))) reject("SPICE_BAD_ANALYSIS", "Analysis directive has invalid numeric arguments.", line); else statements.push({ ...base, kind: "analysis", analysis: kind === "op" ? { kind } : { kind, values: values as number[], tokens: tokens.slice(1) } }); continue; }
    if (directive === ".end") { if (mode !== "editable-circuit" || activeSubckt || tokens.length !== 1) reject("SPICE_MISPLACED_END", "The .end terminator is only allowed once at editable-circuit top level.", line); else { statements.push({ ...base, kind: "terminator" }); sawEnd = true; } continue; }
    reject("SPICE_FORBIDDEN_DIRECTIVE", "This SPICE directive is not in the source allowlist.", line);
  }
  if (activeSubckt) reject("SPICE_UNPAIRED_SUBCKT", "Subcircuit declaration has no matching .ends.", { startLine: activeSubckt.startLine, endLine: activeSubckt.startLine });
  const seen = new Set<string>(); for (const declaration of [...models.map((entry) => entry.name), ...subcircuits.map((entry) => entry.name)]) { const key = declaration.toUpperCase(); if (seen.has(key)) diagnostics.push(diagnostic("SPICE_DUPLICATE_SYMBOL", "Model and subcircuit symbols must be unique case-insensitively.", 1, 1, origin)); seen.add(key); }
  if (mode === "editable-circuit" && statements.length && statements[0].kind === "element") { const title: ParsedSpiceStatement = { text: "", startLine: 1, endLine: 1, scope: { kind: "top-level" }, kind: "title" }; statements.unshift(title); sawTitle = true; }
  const normalizedSource = physical.normalized; if (diagnostics.length) return { ok: false, diagnostics };
  return { ok: true, value: { normalizedSource, statements, declarationBlocks: declarations, models, subcircuits, utf8Bytes: new TextEncoder().encode(normalizedSource).byteLength, sha256: await sha256Hex(normalizedSource) }, diagnostics: sawTitle ? [] : [] };
}

export async function validateProjectModels(project: CircuitProjectV2, origin: SpiceSourceOrigin, bundledManifest: readonly ModelDefinition[]): Promise<DomainResult<CircuitProjectV2>> {
  const diagnostics: Diagnostic[] = []; const models: ModelDefinition[] = [];
  for (const definition of project.models) {
    const parsed = await parseAndValidateSpiceSource(definition.source, definition.origin === "bundled" ? "bundled-model" : origin, "opaque-model");
    if (!parsed.ok) { diagnostics.push(...parsed.diagnostics.map((item) => ({ ...item, location: { ...item.location, modelId: definition.id } }))); continue; }
    const mismatch = definition.sha256 !== parsed.value.sha256 || (definition.kind === "spice-model" && (parsed.value.models.length !== 1 || parsed.value.models[0].name.toUpperCase() !== definition.modelName.toUpperCase() || parsed.value.models[0].family !== definition.deviceFamily)) || (definition.kind === "spice-subckt" && JSON.stringify(definition.interfaces) !== JSON.stringify(parsed.value.subcircuits));
    const manifest = bundledManifest.find((entry) => entry.id === definition.id);
    if (mismatch || (definition.origin === "bundled" && (!manifest || JSON.stringify(manifest) !== JSON.stringify(definition)))) diagnostics.push({ severity: "error", code: "SPICE_MODEL_METADATA_MISMATCH", message: "Model metadata must exactly match its parsed source and bundled manifest.", location: { modelId: definition.id }, blocksRun: true });
    else models.push({ ...definition, source: parsed.value.normalizedSource });
  }
  return diagnostics.length ? { ok: false, diagnostics } : { ok: true, value: { ...project, models }, diagnostics: [] };
}
