/** FLUXLAB workspace: project edits dispatch revision-safe commands and persist locally; simulation remains unavailable until Task 1 qualification. */
import { useEffect, useReducer, useState } from "react";
import { useRoute } from "wouter";
import { applyProjectCommand, projectReducer, type ProjectEditorState } from "../features/editor/project-reducer";
import type { ComponentInstance } from "../domain/project/project-v2";
import { loadProject, saveProject } from "../storage/indexeddb";
import { PropertiesPanel } from "../features/editor/PropertiesPanel";
import { SchematicCanvas } from "../features/editor/SchematicCanvas";
export default function ProjectWorkspace() { const [, params] = useRoute("/project/:projectId"); const [state, dispatch] = useReducer(projectReducer, undefined, () => null as unknown as ProjectEditorState); const [error, setError] = useState<string>(); useEffect(() => { if (!params?.projectId) return; void loadProject(params.projectId).then((result) => { if (!result.ok || !result.value) setError(result.diagnostics.map((item) => item.code).join(",") || "PROJECT_NOT_FOUND"); else dispatch({ type: "hydrate", project: result.value }); }); }, [params?.projectId]); const project = state?.present; if (error) return <main className="flux-page"><h1>{error}</h1></main>; if (!project) return <main className="flux-page"><p>正在打开本地项目…</p></main>; const r2 = project.schematic.components.find((item): item is Extract<ComponentInstance, { kind: "resistor" }> => item.id === "R2" && item.kind === "resistor"); const updateResistance = async (value: number) => { if (!r2 || !Number.isFinite(value) || value <= 0) return; const command = { type: "component/replace" as const, component: { ...r2, params: { resistanceOhm: value } } }; const changed = applyProjectCommand(project, command, new Date().toISOString()); if (changed.ok) { dispatch({ type: "command", command, changedAt: changed.value.updatedAt }); await saveProject(project.revision, changed.value); } }; return <main className="flux-page"><p className="flux-kicker">FLUXLAB / PROJECT</p><h1>{project.title}</h1><p data-testid="project-revision">修订 {project.revision} / 电气 {project.electricalRevision}</p><SchematicCanvas project={project} />{r2 && <PropertiesPanel resistanceOhm={r2.params.resistanceOhm} onApply={(value) => void updateResistance(value)} />}<p>本地保存 · 数值仿真将在 ngspice/WASM 资格化后启用。</p></main>; }
