/** FLUXLAB migration: v1 input is converted only into a reviewable in-memory v2 candidate and never carries old simulated evidence forward. */
import { validateProjectModels } from "../../simulation/spice-source-parser";
import type { LegacyV1CircuitDocument, LegacyV1Component } from "../../legacy/v1-types";
import { bundledModel, projectModelsFromManifest } from "./bundled-models";
import { parseCircuitProjectV2 } from "./project-schema";
import type { CircuitProjectV2, ComponentInstance, ComponentLayout, Diagnostic, ProjectId } from "./project-v2";

export type MigrationResult = { kind: "candidate"; project: CircuitProjectV2; diagnostics: Diagnostic[]; sourceVersion: 1; discardedEvidence: true } | { kind: "rejected"; diagnostics: Diagnostic[] };
const rejected = (code: string, message: string): MigrationResult => ({ kind: "rejected", diagnostics: [{ severity: "error", code, message, blocksRun: true }] });
const finite = (value: unknown, fallback: number) => typeof value === "number" && Number.isFinite(value) ? value : fallback;
const rotation = (value: unknown): ComponentLayout["rotation"] => value === 90 || value === 180 || value === 270 ? value : 0;
function componentFromLegacy(item: LegacyV1Component, models: Set<string>, diagnostics: Diagnostic[]): ComponentInstance | undefined { const id = item.id; const refdes = item.refdes ?? id; if (!id || !refdes) return undefined; if (item.kind === "resistor") return { id, refdes, kind: "resistor", params: { resistanceOhm: finite(item.value, 1000) } }; if (item.kind === "capacitor") return { id, refdes, kind: "capacitor", params: { capacitanceF: finite(item.value, 100e-6) } }; if (item.kind === "inductor") return { id, refdes, kind: "inductor", params: { inductanceH: finite(item.value, 1e-3) } }; if (item.kind === "voltageSource") return { id, refdes, kind: "voltageSource", params: { dcV: finite(item.dcV, 0) } }; if (item.kind === "ground") return { id, refdes: "GND", kind: "ground", params: {} }; if (item.kind === "diode") { models.add("model:fluxled:v1"); return { id, refdes, kind: "diode", modelRef: "model:fluxled:v1", params: { area: 1 } }; } if (item.kind === "switch") { models.add("model:fluxsw:v1"); diagnostics.push({ severity: "error", code: "MIGRATION_SWITCH_REQUIRES_REWIRE", message: "The migrated switch has unconnected cp/cn control pins and must be rewired before a run.", location: { componentId: id }, blocksRun: true }); return { id, refdes, kind: "switch", modelRef: "model:fluxsw:v1", params: {} }; } return undefined; }
export async function migrateV1CircuitDocument(input: unknown, options: { projectId: ProjectId; migratedAt: string }): Promise<MigrationResult> { const legacy = input as Partial<LegacyV1CircuitDocument>; if (!legacy || legacy.schemaVersion !== 1 || !Array.isArray(legacy.components) || !legacy.components.every((item) => item && typeof item === "object" && typeof (item as LegacyV1Component).id === "string")) return rejected("MIGRATION_INVALID_V1", "Input is not a structural v1 circuit document."); const diagnostics: Diagnostic[] = []; const modelIds = new Set<string>(); const components = legacy.components.map((item) => componentFromLegacy(item, modelIds, diagnostics)).filter((item): item is ComponentInstance => Boolean(item)); if (components.length !== legacy.components.length) return rejected("MIGRATION_UNSUPPORTED_COMPONENT", "A legacy component cannot be represented in CircuitProjectV2."); const models = Array.from(modelIds).map(bundledModel); const layoutComponents: Record<string, ComponentLayout> = Object.fromEntries(legacy.components.map((item) => [item.id, { x: finite(item.x, 0), y: finite(item.y, 0), rotation: rotation(item.rotation) }])); const project: CircuitProjectV2 = { schemaVersion: 2, id: options.projectId, title: legacy.title || "已迁移电路", createdAt: options.migratedAt, updatedAt: options.migratedAt, revision: 1, electricalRevision: 1, schematic: { components, wires: [] }, layout: { components: layoutComponents, wireRoutes: {}, viewport: { x: 0, y: 0, zoom: 1 } }, models, analyses: [{ id: "analysis:op", name: "DC operating point", kind: "dc-op", enabledProbes: [] }], probes: [], assertions: [], corners: [], notes: [] }; const schema = parseCircuitProjectV2(project); if (!schema.ok) return { kind: "rejected", diagnostics: schema.diagnostics }; const validated = await validateProjectModels(schema.value, "migration", projectModelsFromManifest()); if (!validated.ok) return { kind: "rejected", diagnostics: validated.diagnostics }; return { kind: "candidate", project: validated.value, diagnostics, sourceVersion: 1, discardedEvidence: true }; }
