/** FLUXLAB templates: deterministic electrical facts only; no pre-run result, lesson completion, hidden initial condition, or solver claim. */
import { validateProjectModels } from "../../simulation/spice-source-parser";
import { bundledModel, projectModelsFromManifest } from "./bundled-models";
import type { CircuitProjectV2, DomainResult, ProjectId } from "./project-v2";

const layout = (items: Array<[string, number, number]>) => ({ components: Object.fromEntries(items.map(([id, x, y]) => [id, { x, y, rotation: 0 as const }])), wireRoutes: {}, viewport: { x: 0, y: 0, zoom: 1 } });
const base = (id: ProjectId, title: string, createdAt: string): Pick<CircuitProjectV2, "schemaVersion" | "id" | "title" | "createdAt" | "updatedAt" | "revision" | "electricalRevision" | "assertions" | "corners" | "notes"> => ({ schemaVersion: 2, id, title, createdAt, updatedAt: createdAt, revision: 1, electricalRevision: 1, assertions: [], corners: [], notes: [] });
async function verifiedTemplate(project: CircuitProjectV2): Promise<DomainResult<CircuitProjectV2>> { return validateProjectModels(project, "project-model", projectModelsFromManifest()); }

export async function createDividerTemplate(projectId: ProjectId, createdAt: string): Promise<DomainResult<CircuitProjectV2>> { return verifiedTemplate({ ...base(projectId, "9 V 分压器", createdAt), schematic: { components: [{ id: "V1", refdes: "V1", kind: "voltageSource", params: { dcV: 9 } }, { id: "R1", refdes: "R1", kind: "resistor", params: { resistanceOhm: 1000 } }, { id: "R2", refdes: "R2", kind: "resistor", params: { resistanceOhm: 2000 } }, { id: "GND", refdes: "GND", kind: "ground", params: {} }], wires: [] }, layout: layout([["V1", 120, 240], ["R1", 380, 140], ["R2", 380, 300], ["GND", 120, 390]]), models: [], analyses: [{ id: "analysis:op", name: "DC operating point", kind: "dc-op", enabledProbes: ["probe:vout"] }], probes: [{ id: "probe:vout", kind: "node-voltage", node: { componentId: "R1", pin: "n" }, label: "Vout" }] }); }
export async function createRcTemplate(projectId: ProjectId, createdAt: string): Promise<DomainResult<CircuitProjectV2>> { return verifiedTemplate({ ...base(projectId, "RC 充电", createdAt), schematic: { components: [{ id: "V1", refdes: "V1", kind: "voltageSource", params: { dcV: 0, transient: { kind: "pulse", initialV: 0, pulsedV: 5, delayS: 0, riseS: 1e-6, fallS: 1e-6, widthS: 4.99, periodS: 5 } } }, { id: "R1", refdes: "R1", kind: "resistor", params: { resistanceOhm: 10_000 } }, { id: "C1", refdes: "C1", kind: "capacitor", params: { capacitanceF: 100e-6 } }, { id: "GND", refdes: "GND", kind: "ground", params: {} }], wires: [] }, layout: layout([["V1", 120, 240], ["R1", 360, 180], ["C1", 570, 300], ["GND", 570, 410]]), models: [], analyses: [{ id: "analysis:transient", name: "RC charge transient", kind: "transient", stepS: 0.01, stopS: 5, enabledProbes: ["probe:vcap"] }], probes: [{ id: "probe:vcap", kind: "node-voltage", node: { componentId: "C1", pin: "p" }, label: "Vcap" }] }); }
export async function createLedTemplate(projectId: ProjectId, createdAt: string): Promise<DomainResult<CircuitProjectV2>> { return verifiedTemplate({ ...base(projectId, "LED 限流", createdAt), schematic: { components: [{ id: "V1", refdes: "V1", kind: "voltageSource", params: { dcV: 5 } }, { id: "R1", refdes: "R1", kind: "resistor", params: { resistanceOhm: 680 } }, { id: "D1", refdes: "D1", kind: "diode", modelRef: "model:fluxled:v1", params: { area: 1 } }, { id: "GND", refdes: "GND", kind: "ground", params: {} }], wires: [] }, layout: layout([["V1", 120, 240], ["R1", 340, 180], ["D1", 570, 260], ["GND", 570, 410]]), models: [bundledModel("model:fluxled:v1")], analyses: [{ id: "analysis:op", name: "LED operating point", kind: "dc-op", enabledProbes: ["probe:led-current"] }], probes: [{ id: "probe:led-current", kind: "branch-current", componentId: "D1", label: "I(D1)" }] }); }
