/** FLUXLAB storage: native IndexedDB is the single browser persistence owner for validated project envelopes. */
import { validateProjectModels } from "../simulation/spice-source-parser";
import { projectModelsFromManifest } from "../domain/project/bundled-models";
import { parseCircuitProjectV2 } from "../domain/project/project-schema";
import type { CircuitProjectV2, Diagnostic, DomainResult, ProjectId } from "../domain/project/project-v2";
export interface ProjectSummary { projectId: ProjectId; title: string; updatedAt: string; revision: number; }
interface Envelope { envelopeVersion: 1; storageVersion: number; project: CircuitProjectV2; listKey: [string, string, string, number]; revisionKey: [string, number, number]; }
const db = () => new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open("fluxlab", 1); request.onupgradeneeded = () => { const database = request.result; const projects = database.createObjectStore("projects", { keyPath: "project.id" }); projects.createIndex("listKey", "listKey"); projects.createIndex("revisionKey", "revisionKey"); database.createObjectStore("runSequences", { keyPath: "projectId" }); database.createObjectStore("runs", { keyPath: "record.runId" }); database.createObjectStore("lessonEvidence", { keyPath: "lessonKey" }); database.createObjectStore("settings", { keyPath: "key" }); }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
const issue = (code: string): Diagnostic => ({ severity: "error", code, message: "Stored project data is unavailable or invalid.", blocksRun: true });
export async function saveProject(expectedRevision: number | null, project: CircuitProjectV2): Promise<DomainResult<CircuitProjectV2>> { const parsed = parseCircuitProjectV2(project); if (!parsed.ok) return parsed; const checked = await validateProjectModels(parsed.value, "stored-model", projectModelsFromManifest()); if (!checked.ok) return checked; const database = await db(); return new Promise((resolve) => { const transaction = database.transaction(["projects", "runSequences"], "readwrite"); const store = transaction.objectStore("projects"); const request = store.get(project.id); request.onsuccess = () => { const current = request.result as Envelope | undefined; if ((expectedRevision === null && current) || (expectedRevision !== null && current?.project.revision !== expectedRevision)) { transaction.abort(); resolve({ ok: false, diagnostics: [issue("STORAGE_REVISION_CONFLICT")] }); return; } const envelope: Envelope = { envelopeVersion: 1, storageVersion: (current?.storageVersion ?? 0) + 1, project: checked.value, listKey: [checked.value.updatedAt, checked.value.id, checked.value.title, checked.value.revision], revisionKey: [checked.value.id, checked.value.revision, checked.value.electricalRevision] }; store.put(envelope); if (!current) transaction.objectStore("runSequences").add({ envelopeVersion: 1, projectId: project.id, nextAttempt: 1, storageVersion: 1 }); }; transaction.oncomplete = () => { database.close(); resolve({ ok: true, value: checked.value, diagnostics: [] }); }; transaction.onerror = transaction.onabort = () => { database.close(); if (!transaction.error) return; resolve({ ok: false, diagnostics: [issue("STORAGE_WRITE_FAILED")] }); }; }); }
export async function loadProject(projectId: ProjectId): Promise<DomainResult<CircuitProjectV2 | null>> { const database = await db(); const raw = await new Promise<Envelope | undefined>((resolve, reject) => { const tx = database.transaction("projects", "readonly"); const request = tx.objectStore("projects").get(projectId); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); database.close(); if (!raw) return { ok: true, value: null, diagnostics: [] }; const parsed = parseCircuitProjectV2(raw.project); if (!parsed.ok) return { ok: false, diagnostics: [issue("STORAGE_INVALID_PROJECT"), ...parsed.diagnostics] }; return validateProjectModels(parsed.value, "stored-model", projectModelsFromManifest()); }
export async function listProjects(): Promise<DomainResult<ProjectSummary[]>> { const database = await db(); const values = await new Promise<Envelope[]>((resolve, reject) => { const request = database.transaction("projects", "readonly").objectStore("projects").getAll(); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); database.close(); return { ok: true, value: values.map((entry) => ({ projectId: entry.project.id, title: entry.project.title, updatedAt: entry.project.updatedAt, revision: entry.project.revision })).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)), diagnostics: [] }; }
export async function deleteProject(projectId: ProjectId): Promise<DomainResult<null>> { const database = await db(); return new Promise((resolve) => { const transaction = database.transaction(["projects", "runSequences", "runs", "lessonEvidence", "settings"], "readwrite"); transaction.objectStore("projects").delete(projectId); transaction.objectStore("runSequences").delete(projectId); transaction.oncomplete = () => { database.close(); resolve({ ok: true, value: null, diagnostics: [] }); }; transaction.onerror = () => { database.close(); resolve({ ok: false, diagnostics: [issue("STORAGE_DELETE_FAILED")] }); }; }); }
